### ISSUE TITLE
[UI] iOS 3차 과제 전체 레이아웃 구성

### ISSUE THREAD

**Issue by YoonAh-dev** [29th-WE-SOPT-iOS-Part/ShinYunA#12]
## 📌  Feature Issue
TableView, CollectionView를 사용해서 유튜브 홈을 구성합니다.

## 📝  To-do

- [x] TableView를 사용해서 유튜브 메인 화면 구성
- [x] CollectionView 2개 View 구성
- [x] 전체 헤더 구성
