### ISSUE TITLE
[FEAT] iOS 7차 과제

### ISSUE THREAD

**Issue by YoonAh-dev** [29th-WE-SOPT-iOS-Part/ShinYunA#19]
## 📌  Feature Issue
7차 과제를 구현합니다.
1. Video에 있는 ImageView를 터치하도록 구현
2. 터치했을 시에 새로운 뷰 나타내기

## 📝  To-do

- [x] 새로운 VideoVC 생성
- [x] 내부 Layout 구현
- [x] ImageView, UITapGesture를 통해서 터치 구현
- [x] delegate를 사용해서 ImageView를 터치했을 시 새로운 뷰가 Present되도록 구현
