### ISSUE TITLE
[UI] iOS 1차 과제 UI 구성

### ISSUE THREAD

**Issue by YoonAh-dev** [29th-WE-SOPT-iOS-Part/ShinYunA#2]
## 📌  Feature Issue
1주차 과제는 로그인, 회원가입, 확인화면 UI 구성과 화면전환 그리고 데이터 전달입니다!

전체 화면 UI를 구성합니다.

## 📝  To-do

▶️ UI 구성하기
- [x]  로그인 화면 UI 구성하기
- [x]  회원가입 화면 UI 구성하기
- [x]  확인 화면 UI 구성하기
