### ISSUE TITLE
[FEAT] iOS 1차 과제 화면 전환 및 기능 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [29th-WE-SOPT-iOS-Part/ShinYunA#3]
## 📌  Feature Issue
1주차 과제는 로그인, 회원가입, 확인화면 UI 구성과 화면전환 그리고 데이터 전달입니다!

화면 전환 및 데이터 이동을 구현합니다.

## 📝  To-do

▶️ 화면 전환하기
- [x]  로그인 화면 → 회원가입 화면 으로 push로 화면전환하기
- [x]  로그인 화면 → 확인 화면 으로 present로 화면전환하기
- [x]  회원가입 화면 → 확인 화면 으로 present로 화면전환하기

▶️ 기능 구현하기
- [x]  로그인 화면에서 적은 이름을 확인 화면에서 띄우기
- [x]  회원가입 화면에서 적은 이름을 확인 화면에서 띄우기
